# Generated by Django 6.0.4 on 2026-05-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_created_alter_post_publish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('name', models.TextField(max_length=250, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.TextField(verbose_name='Phone')),
                ('subject', models.TextField(verbose_name='Subject')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
