# Generated by Django 6.0.4 on 2026-06-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('sky', 'Sky'), ('programming', 'Programming'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
