# Generated by Django 5.2.16 on 2026-08-13 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved_by',
            field=models.ManyToManyField(null=True, related_name='saved_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
