# Generated by Django 5.2.16 on 2026-08-22 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_post_total_likes_post_social_post_total_l_b22ce0_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='saved_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='saved_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
